---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sblockservicepatch
spec:
  crd:
    spec:
      names:
        kind: K8sBlockServicePatch
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            users:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockservicepatch

        violation[{"msg": msg}] {
            input.review.kind.kind == "Service"
            input.review.operation == "UPDATE"
            input.review.subResource == "status"
            input.review.requestSubResource == "status"
            user := input.review.userInfo.username
            allowed := {good | alloweduser:= input.parameters.users[_];  good = identical(user, alloweduser)}
            not any(allowed)
            msg := sprintf("CVE-2020-8554 was detected on service %v/%v by user: %v", [input.review.namespace, input.review.name, user])
        }

        identical(user1, user2){
            user1 == user2
        }